### ISSUE TITLE
关于json格式的问题

### ISSUE THREAD

**Issue by paulAndKey** [kajweb/dict#2]
看了看json格式，应该是数组，但是头和尾又没有[]括号包含，自己加了[], 发现数组中的每个字典都没有“,”号做分隔，不知道怎么解析了，我这边是iOS，本来想着做一个简单的毕业设计app，看着数据格式发愁，不知道作者有没有什么解决办法？

**Comment by kajweb** [comment]
[使用方法](https://github.com/kajweb/dict/wiki/使用方法)
